### ISSUE TITLE
Running for a predetermined amount of time

### ISSUE THREAD

**Issue by vidalt** [acco93/filo#3]
Dear Luca, 
Thank you so much for sharing this code, it greatly contributes to the routing community.
I had a quick question: in many algorithmic comparisons, it makes sense to compare methods for the same amount of time on a computer. Is there currently an option in the code that permits running the code for a predetermined amount of time (instead of a predetermined number of iterations?).
Kind Regards,
--Thibaut

**Comment by acco93** [comment]
Hi Thibaut,
thank you for your interest.

I've just added the option (also thanks to @c4v4 for porting the simulated annealing).

Having 2 projects makes the process a little bit awkward.
You'll have to first pull, rebuild and reinstall cobra.
Then, you can pull and rebuild filo by including `-DTIMEBASED_TERMINATION=1` in the cmake command.

Finally, you can specify the total number of seconds in the executable by using `--time`.

Best, Luca

**Comment by vidalt** [comment]
Hello Luca and @c4v4,
That's fantastic, thanks to both of you for the super-fast feedback!
--Thibaut
